config/routes.rb
# -*- encoding : utf-8 -*-
Sapphire::Application.routes.draw do

  match '/synchronisation', :to => "switchs_management#synchronisation"
  resources :logs


  resources :roles


	# En vrac
		get '/computers/reload', :controller => 'computers', :action => 'reload'
		resources :computers, :only => [:index, :show]

		get '/payments/reload', :controller => 'payments', :action => 'reload'
		resources :payments do
			member do
				get 'cash'
				get 'by_treasurer'
				get 'reset_status'
			end
		end

		# Sessions
		delete "deconnexion", to: "sessions#destroy", as: "deconnexion"
		get 'connexion', to: 'sessions#new', as: :connexion

		root to: "activities#index"

	# Les différentes ressources de l'appli

		resources :sessions
		resources :admins

		get '/mailings/reload', :controller => 'mailings', :action => 'reload'
		resources :mailings

		get '/rooms/reload', :controller => 'rooms', :action => 'reload'
		resources :rooms

		get '/adherents/reload', :controller => 'adherents', :action => 'reload'
		get '/adherents/index_discourse', :controller => 'adherents', :action => 'index_discourse'
		resources :adherents do
			member do
				get 'new_discourse'
				put 'create_discourse'
			end
			resources :computers
			resources :payments
			get "credit/destroy"
		end
		
		get '/generic_dns_entries/reload', :controller => 'generic_dns_entries', :action => 'reload'
	  	resources :generic_dns_entries
	  	resources :computer_dns_entries do
			resources :alias_dns_entries
		end
		resources :vlans

		get '/switches/reload', :controller => 'switches', :action => 'reload'
		resources :switches do
			resources :ports
		end
	
end

app/models/adherent.rb
# -*- encoding : utf-8 -*-
class Adherent < ActiveRecord::Base

require 'discourse_api/discourse_api'


scope :not_archived, -> { where(archived: false)}

# Surveillance par la gem public_activity
	include PublicActivity::Common

# --------------------------------------------------------------------------------------------------
#	Attributs
# --------------------------------------------------------------------------------------------------

	attr_accessible :first_name, :last_name, :password, :password_confirmation, :email, :username, :promotion, :room, :supelec_email, :use_supelec_email,
		:rezoman, :resident, :supelec,
		:computers_attributes, :credit_attributes
			# La première ligne correspond à l'identité à proprement dit de l'adhérent
			# La seconde ligne à des booléens qui permettent d'identifier les droits de l'adhérent
				# Rezoman : permet de se connecter dans toutes les chambres, et de ne pas payer sa connexion.
				# Resident : Un resident n'a pas d'ordinateurs, de solde ou de connexion.
				# Supelec : un supelec a le droit à un compte discourse, et est sur le VLAN::Supelec
			# La dernière ligne permet la création d'un compte adhérent complet en un seul formulaire.

	# ne sont pas stockés dans la base de donnée, ils permet simplement de réaliser les formulaires.
	attr_accessor :password

# --------------------------------------------------------------------------------------------------
#	Associations
# --------------------------------------------------------------------------------------------------

	has_many :mailings, inverse_of: :adherent 	# Un adhérent peut être propriétaire de mailings

	has_one :room, inverse_of: :adherent	# Un adhérent resident a une chambre

	# Association forte
	has_many :computers, dependent: :destroy, inverse_of: :adherent
	has_one :credit, dependent: :destroy, inverse_of: :adherent

# --------------------------------------------------------------------------------------------------
#	Actions avant sauvegarde et validation
# --------------------------------------------------------------------------------------------------

	before_validation :ensure_consistency

	before_save :encrypt_password
	before_save { |adherent| adherent.email = adherent.email.downcase}

# --------------------------------------------------------------------------------------------------
#	Validations
# --------------------------------------------------------------------------------------------------

	validates :first_name, :last_name, presence: true
	validates :email, presence: true, uniqueness: true,
		format: { with: /^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/ }
	
	# S'il s'agit d'un supélec :
	validates :password, confirmation: true, presence: true, length: {minimum: 6}, if: :should_validate_password?
	validates :promotion, presence: true, if: :supelec?
	validates :username, uniqueness: true, length: {minimum: 3}, presence: true,
		:format => { :with => /^([a-zA-Z0-9_\-\.]+)$/ }, if: :supelec?
	validates :supelec_email, uniqueness: true, presence: true, if: :supelec?
	validates :supelec_email, format: { with: /^([a-zA-Z0-9_\-\.]+)$/ }, if: :supelec?

	# S'il s'agit d'un résident :
	validates :credit, presence: true, if: :resident?
	validates :room, presence: true, if: :resident?

# --------------------------------------------------------------------------------------------------
#	Nested forms
# --------------------------------------------------------------------------------------------------

	accepts_nested_attributes_for :computers, reject_if: :not_resident?, :allow_destroy => true
	accepts_nested_attributes_for :credit, reject_if: :not_resident?

# --------------------------------------------------------------------------------------------------
#	Création du compte discourse 
# --------------------------------------------------------------------------------------------------

	#after_create :create_discourse_user

# --------------------------------------------------------------------------------------------------
#	Méthodes
# --------------------------------------------------------------------------------------------------

# Création d'un utilisateur discourse

	def create_discourse_user 
		if supelec?
			client = DiscourseApi::Client.new("193.54.193.2")
			client.api_key = "59f0959060761f1414c6cf7c23b843841059b4bf7d34ad808d979e4598faab27"
			client.api_username = "Lerik"
			client.create_user(name: full_name, email: email_to_use, password: password, username: username)
			self.discourse_created = true
			self.save
		end
	end


# Devrait être déplacé pour factorisation du code avec les admins
		def encrypt_password
			if password.present?
				self.password_salt = BCrypt::Engine.generate_salt
				self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
			end
		end

	# Modifie les données pour s'assurer ques les informations de l'adhérent soient cohérentes
		def ensure_consistency
			if not_resident?
				room = nil
			end
			if not_supelec?
				promotion = nil
				password = nil
				username = nil
				supelec_email = nil				
			end
		end

# --------------------------------------------------------------------------------------------------
#	Helpers
# --------------------------------------------------------------------------------------------------

	def room_id
		room.id if room
	end
	
	def full_name
		self.first_name + " " + self.last_name
	end

	def full_supelec_address
		if supelec_email
			supelec_email + "@supelec.fr"
		end
	end

	def email_to_use
		if use_supelec_email
			supelec_email
		else
			email
		end
	end

	def actif?
		credit and credit.actif?
	end

	def should_be_disconnected?
		!credit or credit.should_be_disconnected?
	end

	def should_validate_password?
		(self.password && !self.password.blank?) || ( supelec? && self.new_record?)
	end

	def credit_value
		self.credit.value
	end

	def room_number
		self.room.full_address
	end

private
	
		def not_resident?
			not resident?
		end

		def not_supelec?
			not supelec?
		end
end

app/controllers/adherents_controller.rb
# -*- encoding : utf-8 -*-
class AdherentsController < ApplicationController

# Charge @adherent par id, ainsi que les autorisations du controller
load_and_authorize_resource except: :create
authorize_resource only: :create

  def index
    @adherents = Adherent.includes({:credit => :active_payments}, :room).where(:archived => params[:archived].to_bool)
    respond_to do |format|
      format.json { render json: @adherents, each_serializer: AdherentSerializer }
      format.html
    end
  end

  def show
  end

  def new
    @computer = @adherent.computers.build

    @credit = @adherent.build_credit
    @credit.payments.build
  end


  def create

    params[:adherent][:room] = Room.find_by_id(params[:adherent][:room])
    @adherent = Adherent.new(params[:adherent])
    @adherent.credit.payments.first.admin = current_admin if @adherent.credit

    respond_to do |format|
      if @adherent.save
        @adherent.create_discourse_user
        @adherent.create_activity :create, owner: current_admin
        format.json { render json: @adherent, status: :created, location: @adherent }
      else        
        flash.now[:error] = @adherent.errors.full_messages

        @adherent.computers.build if @adherent.computers.empty?
        @computer = @adherent.computers.first

        @adherent.build_credit unless @adherent.credit
        @credit = @adherent.credit
        @credit.payments.build if @credit.payments.empty?
        format.js { render action: :new}
      end  
    end
  end


  def edit
  end

  def update
    params[:adherent][:room] = Room.find_by_id(params[:adherent][:room])

    respond_to do |format|
      if @adherent.update_attributes(params[:adherent])

        if @room
          @room.adherent = @adherent
          @romm.save
        end
        
        @adherent.create_activity :update, owner: current_admin
        format.js { head :no_content }
        format.json { render json: @adherent, status: :updated, location: @adherent }
      else        
        flash.now[:error] = @adherent.errors.full_messages
        format.js { render :edit}
      end  
    end
  end

  def destroy
    # On archive au lieu de supprimer de la base de donnée
    @adherent.update_attribute(:archived, true)

    @adherent.create_activity :destroy, owner: current_admin

    respond_to do |format|
      format.html { redirect_to adherents_url }
      format.json { head :no_content }
    end
  end

  def reload
    @adherents = Adherent.includes({:credit => :active_payments}, :room).where(:archived => params[:archived].to_bool)
    respond_to do |format|
      format.html { render partial: "index_table" }
    end
  end

  def new_discourse

  end

  def create_discourse
    respond_to do |format|
      if @adherent.update_attributes(params[:adherent])
        @adherent.create_discourse_user
        format.js { head :no_content }
      else        
        flash.now[:error] = @adherent.errors.full_messages
        format.js { render :new_discourse}
      end  
    end
  end

  def index_discourse
    @adherents = Adherent.where(:archived => params[:archived].to_bool)
  end

end

app/helpers/adherents_helper.rb
# -*- encoding : utf-8 -*-
module AdherentsHelper
end

app/views/adherents/_adherent_form.html.haml
.controls.btn-group.activable
	%button.btn#resident-btn{"data-target" => "#if_resident, #computers-form, #payment-form", "data-toggle" => "collapse"}
		Résident
	%button.btn#supelec-btn{"data-target" => "#if_supelec", "data-toggle" => "collapse"}
		Supélec
	%button.btn#rezoman-btn{"data-target" => "#if_supelec", "data-toggle" => "collapse", style: 'display: none'}
		Rezoman

.controls
	.input-append
		= f.input_field :first_name, placeholder: "Prénom"
		%span.add-on
			%i.icon-user{rel: "tooltip", title: "Prénom", style: "margin-top: 10px"}
	.input-append
		= f.input_field :last_name, placeholder: "Nom de famille"
		%span.add-on
			%i.icon-user{rel: "tooltip", title: "Nom de famille", style: "margin-top: 10px"}


.input-append
	= f.input_field :email, placeholder: "E-mail"
	%span.add-on
		%i.icon-envelope-alt{rel: "tooltip", title: "E-mail", style: "margin-top: 10px"}

%div{style: 'display: none'}
	= f.hidden_field :resident, value: (if f.object.resident then "true" else "false" end)
	= f.hidden_field :supelec, value: (if f.object.supelec then "true" else "false" end)
	= f.hidden_field :rezoman, value: (if f.object.rezoman then "true" else "false" end)

app/views/adherents/_edit.html.haml
.modal-header
	%button.close{ type:"button", 'data-dismiss' => "modal"}
		%i.icon-remove

	%h3
		Edition de
		= @adherent.full_name

	= bootstrap_flash

= simple_form_for @adherent, validate: true, remote: true do |f|	

	.modal-body
		= render partial: "form", locals: {f: f}

	.modal-footer
		= f.submit "Editer", {class: "btn btn-primary"}

app/views/adherents/_form.html.haml
%ul.nav.nav-tabs
	%li.active
		= link_to "Adhérent", "#adherent", "data-toggle" => "tab"
	%li
		= link_to "Résidence", "#resident", id: "resident-tab", "data-toggle" => "tab"
	%li
		= link_to "Supélec", "#supelec", id: "supelec-tab", "data-toggle" => "tab"

.tab-content
	.tab-pane.active#adherent

		= render 'adherent_form', f: f

	.tab-pane#resident

		= f.input_field :room, collection: Room.not_archived, label_method: :address_and_adherent, id: "rooms-select", style: 'width: 254px; margin-bottom: 10px;', selected: @adherent.room_id

		- if @adherent.new_record?
			%hr
			%h2 Ordinateur

			= f.simple_fields_for :computers do |builder|
				= render 'computers/form', f: builder	
			
			%hr
			%h2 Paiement

			= f.simple_fields_for :credit do |builder|
				= builder.simple_fields_for :payments do |payment_builder|
					= render 'payments/form', f: payment_builder

	.tab-pane#supelec

		.controls
			= f.input_field :password, placeholder: "Mot de passe"
			= f.input_field :password_confirmation, placeholder: "Confirmation du mot de passe"

		.controls
			= f.input_field :username, placeholder: "Username"
			= f.input_field :promotion, as: :select, collection: (Time.now.year-5...Time.now.year+5), id: "years-select", style: 'width: 220px;'

		.controls
			.input-append
				= f.input_field :supelec_email, required: true, id: "appendedInput", :placeholder => "Adresse Supélec"
				%span.add-on{style: 'margin-bottom: 3px;', rel: "tooltip", title: "E-mail Supélec"}
					= "@supelec.fr"

			%button.btn#supelec-mail-button{style: "margin-bottom: 2px;"} Utiliser l'adresse Supélec			

			= f.hidden_field :use_supelec_email, id: "supelec-mail-check"

app/views/adherents/_index_table.html.haml
%table#adherents{style: "overflow: visible"}
	%thead
		%tr
			%th Etat
			%th Nom
			%th Type
			%th Temps
			%th Date d'expiration
			%th Chambre
			%th 
	%tbody
		-@adherents.each do |adherent|
			%tr
				%td{:class => if adherent.should_be_disconnected? then "red" else "green" end}
				%td
					= adherent.full_name
				%td
					- if adherent.rezoman
						%i.icon-linux.icon-large{rel: "tooltip", title: "Rezoman", style: "margin-right: 5px"}
					- if adherent.resident
						%i.icon-home.icon-large{rel: "tooltip", title: "Résident", style: "margin-right: 5px"}
					- if adherent.supelec
						%i.icon-bolt.icon-large{rel: "tooltip", title: "Supélec"}
					- unless adherent.resident || adherent.supelec || adherent.rezoman
						\--

				%td
					- if adherent.credit
						= adherent.credit.time_value
				%td
					- if adherent.credit
						= adherent.credit.end_of_adhesion

				%td
					- if adherent.room
						= adherent.room.full_address
					- else
						\--
				%td.actions
					= link_to adherent_path(adherent.id), class:"btn btn-success" do
						%i.icon-eye-open.icon-large
						Voir
					.btn-group{style: "margin-top: 2px"}
						= link_to edit_adherent_path(adherent.id), class:"btn btn-warning", remote: true, "data-toggle" => 'modal', "data-target" => '#modal-window'  do
							%i.icon-pencil.icon-large
						%button.btn.btn-warning.dropdown-toggle{"data-toggle" => "dropdown"}
							%span.caret
						%ul.dropdown-menu
							%li
								= link_to new_adherent_computer_path(adherent.id), remote: true, "data-toggle" => 'modal', "data-target" => '#modal-window'  do
									Nouvel ordinateur
							%li
								= link_to new_adherent_payment_path(adherent.id), remote: true, "data-toggle" => 'modal', "data-target" => '#modal-window'  do
									Nouveau paiement
					= link_to adherent_path(adherent.id), class:"btn btn-danger remote-delete", :method => :delete do
						%i.icon-trash.icon-large
						Supprimer

app/views/adherents/_new.html.haml
.modal-header
	%button.close{ type:"button", 'data-dismiss' => "modal"}
		%i.icon-remove

	%h3 Rézotage

	= bootstrap_flash

= simple_form_for @adherent, validate: true, remote: true do |f|	

	.modal-body
		= render "form", f: f

	.modal-footer
		= f.submit "Rézoter", {class: "btn btn-primary"}

app/views/adherents/_new_discourse.html.haml
.modal-header
	%button.close{ type:"button", 'data-dismiss' => "modal"}
		%i.icon-remove

	%h3 Création d'un compte Discourse

	= bootstrap_flash

= simple_form_for @adherent, validate: true, remote: true, :url => create_discourse_adherent_path(@adherent) do |f|	

	.modal-body
		= f.input :username

		= f.input :password

		= f.input :password_confirmation

	.modal-footer
		= f.submit "Créer", {class: "btn btn-primary"}

app/views/adherents/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'edit') %>");

$("#rezoman-btn").show();

// Résident et/ou supélec
init_buttons();
adherent_is_resident_supelec_rezoman();
activate_button();

// Moyen de paiement
payment_is_cheque_or_liquid();
choose_button();


// Tooltips
$("[rel='tooltip']").tooltip();

// Selects
$('#rooms-select').select2({
  placeholder: "Chambre"
});
$('#years-select').select2({
  placeholder: "Promotion"
});

$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
    reload_adherents();
  });

app/views/adherents/index.html.haml
- content_for :title do
	Liste des adhérents

#wrapper
	= render partial: 'index_table'

app/views/adherents/index_discourse.html.haml
- content_for :title do
	Liste des adhérents

#wrapper
	%table#discourse{style: "overflow: visible"}
		%thead
			%tr
				%th Nom
				%th Créé
				%th 
		%tbody
			-@adherents.each do |adherent|
				%tr
					%td
						= adherent.full_name
					%td
						= adherent.discourse_created
					%td.actions
						= link_to new_discourse_adherent_path(adherent.id), class:"btn btn-warning", remote: true, "data-toggle" => 'modal', "data-target" => '#modal-window' do
							%i.icon-eye-open.icon-large
							Créer

app/views/adherents/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'new') %>");

// Résident et/ou supélec
init_buttons();
adherent_is_resident_supelec_rezoman();
activate_button();

// Moyen de paiement
payment_is_cheque_or_liquid();
choose_button();

// Utiliser ou non l'e-mail supélec
use_supelec_mail_button();

// Tooltips
$("[rel='tooltip']").tooltip();

// Selects
$('#rooms-select').select2({
  placeholder: "Chambre"  
});
$('#years-select').select2({
  placeholder: "Promotion"
});

// Faire disparaitre le modal quand la requête réussie
$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
    if($("#adherents").length > 0){
      reload_adherents();
    }
  });

app/views/adherents/new_discourse.js.erb
$("#modal-window").html("<%= escape_javascript(render 'new_discourse') %>");

$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
  });

app/views/adherents/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_adherent_path(@adherent)
\|
= link_to 'Back', adherents_path