config/routes.rb
# -*- encoding : utf-8 -*-
Sapphire::Application.routes.draw do

  match '/synchronisation', :to => "switchs_management#synchronisation"
  resources :logs


  resources :roles


	# En vrac
		get '/computers/reload', :controller => 'computers', :action => 'reload'
		resources :computers, :only => [:index, :show]

		get '/payments/reload', :controller => 'payments', :action => 'reload'
		resources :payments do
			member do
				get 'cash'
				get 'by_treasurer'
				get 'reset_status'
			end
		end

		# Sessions
		delete "deconnexion", to: "sessions#destroy", as: "deconnexion"
		get 'connexion', to: 'sessions#new', as: :connexion

		root to: "activities#index"

	# Les différentes ressources de l'appli

		resources :sessions
		resources :admins

		get '/mailings/reload', :controller => 'mailings', :action => 'reload'
		resources :mailings

		get '/rooms/reload', :controller => 'rooms', :action => 'reload'
		resources :rooms

		get '/adherents/reload', :controller => 'adherents', :action => 'reload'
		get '/adherents/index_discourse', :controller => 'adherents', :action => 'index_discourse'
		resources :adherents do
			member do
				get 'new_discourse'
				put 'create_discourse'
			end
			resources :computers
			resources :payments
			get "credit/destroy"
		end
		
		get '/generic_dns_entries/reload', :controller => 'generic_dns_entries', :action => 'reload'
	  	resources :generic_dns_entries
	  	resources :computer_dns_entries do
			resources :alias_dns_entries
		end
		resources :vlans

		get '/switches/reload', :controller => 'switches', :action => 'reload'
		resources :switches do
			resources :ports
		end
	
end

app/models/room.rb
# -*- encoding : utf-8 -*-
class Room < ActiveRecord::Base

scope :not_archived, -> { where(archived: false)}

# Surveillance par la gem public_activity
	include PublicActivity::Common

# Attributs et associations	
	attr_accessible :adherent_id, :building, :number, :port_id

	belongs_to :adherent, inverse_of: :room
	belongs_to :port, inverse_of: :room

#Validations. Une chambre peut-être vide et sans ip-phone !
	validates :number, presence: true, uniqueness: {scope: :building}
	validates :building, presence: true
	#validates :port, presence: true


	
	def full_address
		self.building + self.number
	end

	def address_and_adherent
		return self.full_address unless self.adherent
		self.full_address + ' (' + self.adherent.full_name + ')'
	end

end

app/controllers/rooms_controller.rb
# -*- encoding : utf-8 -*-
class RoomsController < ApplicationController
  include RoomsHelper

  before_filter :load_buildings

# Charge @room par id, ainsi que les autorisations du controller
  load_and_authorize_resource

  def index
    @rooms = Room.includes(:adherent, {port: :switch}).where(:archived => params[:archived].to_bool)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end


  def show
  end

  def new
  end

  def edit
  end

  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save

        @room.create_activity :create, owner: current_admin
        format.json { render json: @rooms, status: :created, location: @rooms }
      else
        flash.now[:error] = @room.errors.full_messages
        format.js { render action: :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update_attributes(params[:room])

        @room.create_activity :update, owner: current_admin

        format.js { head :no_content }
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        flash.now[:error] = @room.errors.full_messages
        format.js { render action: :edit}
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    # On archive au lieu de supprimer de la base de donnée

    respond_to do |format|
      @room.update_attribute(:archived, true)
      @room.create_activity :destroy, owner: current_admin
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end

  def reload
    @rooms = Room.where(:archived => params[:archived].to_bool)
    respond_to do |format|
      format.html { render partial: "index_table" }
    end
  end
end

app/helpers/rooms_helper.rb
# -*- encoding : utf-8 -*-
module RoomsHelper

	# Liste des bâtiments pris en charge par l'application.
	# Les rajouter ici permet d'y avoir accès pour toutes les vues.
	def load_buildings
		@building_list = ['A', 'B', 'C', 'D', 'H']
	end

end

app/views/rooms/_edit.html.haml
.modal-header
    %button.close{ type:"button", 'data-dismiss' => "modal"}
        %i.icon-remove

    

    %h3 Création d'une chambre

    .alert.alert-block{style: "margin-bottom: 5px; margin-top: 10px;"}
        %h4 
            %i.icon-warning-sign.icon-large
            Attention   
        Les chambres devraient être généré via la commande rake populate:rooms. Modifiez ce script si l'architecture de la rez change.
   
    = bootstrap_flash


= simple_form_for @room, validate: true, remote: true do |f|

    .modal-body
        = render partial: "form", locals: {f: f}  

    .modal-footer
        = f.submit "Créer", {class: "btn btn-primary"}

app/views/rooms/_form.html.haml
.controls
	= f.input_field :building, as: :select, class: "label-field short-field", collection: @building_list, id: "buildings-select", style: "width: 100px"
		
	.input-append
		= f.input_field :number, class: "label-field", :placeholder => "Numéro de la chambre"
		%span.add-on
			%i.icon-male{rel: "tooltip", title: "Numéro de la chambre", style: "margin-top: 10px", "data-placement" => "bottom"}

= f.input_field :port, collection: Port.not_archived, label_method: :designation, id: "ports-select", style: 'width: 254px; margin-bottom: 10px;'

app/views/rooms/_index_table.html.haml
%table#rooms
  %thead
    %tr
      %th Adresse
      %th Locataire
      %th Connexion
      %th 
        = link_to new_room_path, class:"btn btn-inverse", "data-toggle" => 'modal', "data-target" => '#modal-window', remote: true do
          %i.icon-plus
          Nouvelle chambre
  %tbody
    -@rooms.each do |room|
      %tr
        %td
          = room.full_address
        %td
          - if room.adherent
            = link_to room.adherent.full_name, room.adherent
          - else
            \--
        %td
          - if room.port
            - switch = room.port.switch
            = link_to switch.description, switch_path(switch)
            \:
            = link_to room.port.number.to_s, switch_port_path(switch, room.port)
          - else
            \--
        %td.actions
          = link_to room_path(room), "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-success", remote: true do
            %i.icon-eye-open.icon-large
            Voir
          = link_to edit_room_path(room), "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-warning", remote: true do
            %i.icon-pencil.icon-large
            Editer
          = link_to room_path(room), class:"btn btn-danger remote-delete", :method => :delete do
            %i.icon-trash.icon-large
            Supprimer

app/views/rooms/_new.html.haml
.modal-header
    %button.close{ type:"button", 'data-dismiss' => "modal"}
        %i.icon-remove

    

    %h3 Création d'une chambre

    .alert.alert-block{style: "margin-bottom: 5px; margin-top: 10px;"}
        %h4 
            %i.icon-warning-sign.icon-large
            Attention   
        Les chambres devraient être généré via la commande rake populate:rooms. Modifiez ce script si l'architecture de la rez change.
   
    = bootstrap_flash


= simple_form_for @room, validate: true, remote: true do |f|

    .modal-body
        = render partial: "form", locals: {f: f}  

    .modal-footer
        = f.submit "Créer", {class: "btn btn-primary"}

app/views/rooms/_show.html.haml
.modal-header
	%button.close{ type:"button", 'data-dismiss' => "modal"}
		%i.icon-remove

	%h3= @room.full_address

.modal-body
	%p
		%b Building:
		= @room.building
	%p
		%b Number:
		= @room.number
	%p
		%b Adherent:
		= @room.adherent

app/views/rooms/edit.html.haml
%h1 Editing room


= simple_form_for @room do |f|
    = render partial: "form", locals: {f: f}  
    = f.submit "Modifier", {class: "btn btn-primary btn-large btn-block"}

= link_to 'Show', @room
\|
= link_to 'Back', rooms_path

app/views/rooms/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'edit') %>");

// Tooltips
$("[rel='tooltip']").tooltip();

// Selects
$('#buildings-select').select2({
  placeholder: "Bâtiment"
});

$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
    reload_rooms();
  });

app/views/rooms/index.html.haml
- content_for :title do
  Liste des chambres

#wrapper
  = render partial: 'index_table'

app/views/rooms/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'new') %>");

// Tooltips
$("[rel='tooltip']").tooltip();

// Selects
$('#buildings-select').select2({
  placeholder: "Bâtiment"
});

$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
    reload_rooms();
  });

app/views/rooms/show.html.haml
%p#notice= notice

%p
  %b Building:
  = @room.building
%p
  %b Number:
  = @room.number
%p
  %b Adherent:
  = @room.adherent

= link_to 'Edit', edit_room_path(@room)
\|
= link_to 'Back', rooms_path

app/views/rooms/show.js.erb
$("#modal-window").html("<%= escape_javascript(render 'show') %>");

$("[rel='tooltip']").tooltip();